### ISSUE TITLE
The CPU architecture "arm64" is incompatible with this module

### ISSUE THREAD

**Issue by wulv** [nut-tree/TemplateMatcher#11]
```
error @nut-tree/template-matcher@1.0.1: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.
```

**Comment by s1hofmann** [comment]
This is known and also wont change since I stopped actively maintaining https://github.com/nut-tree/opencv4nodejs.

Access to an `arm64` and future proof image search plugin is granted to project sponsors, for more info please refer to this [blog post](https://nutjs.dev/blog/new-years-news) or my [GitHub sponsoring profile](https://github.com/sponsors/s1hofmann)

**Comment by Justiniscoding** [comment]
It works on my m2 macbook, all you have to do is install rosetta 2 by running the following command in terminal:
`softwareupdate --install-rosetta --agree-to-license`
